name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Lowlighter 
      - name: Generate Unified GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.READMESTATISTICS }}
          user: xsha256
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # 3. Tarjeta de lenguajes 
      - name: Generate Top Langs SVG
        uses: stats-organization/github-readme-stats-action@main
        with:
          token: ${{ secrets.READMESTATISTICS }}
          card: top-langs
          path: generated-top-langs.svg
          options: username=xsha256&langs_count=11&theme=radical&show_icons=true&exclude_repo=${{ secrets.REPOS_OCULTOS }}

      # 4. Tarjeta de estadísticas adicionales 
      - name: Generate Additional Stats SVG
        uses: stats-organization/github-readme-stats-action@main
        with:
          token: ${{ secrets.READMESTATISTICS }}
          card: stats
          path: generated-additional-stats.svg
          options: username=xsha256&show_icons=true&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage,issue_comments&theme=chartreuse-dark&count_private=true&exclude_repo=${{ secrets.REPOS_OCULTOS }}

      # 5. los SVGs 
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          mkdir -p /tmp/stats-assets
          cp generated-top-langs.svg generated-additional-stats.svg /tmp/stats-assets/
          
          git fetch origin main
          git reset --hard origin/main
          
          cp /tmp/stats-assets/* ./
          
          git add generated-top-langs.svg generated-additional-stats.svg
          git diff-index --quiet HEAD || git commit -m "docs: update separated stats svgs"
          git push origin main
