name: Metrics
on:
  # Ejecuta el robot cada 24 horas a medianoche
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente si quieres actualizarlo ya
  workflow_dispatch:
  # Se actualiza cuando cambias algo en tu README
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Aquí usa el secreto que acabas de guardar
          token: ${{ secrets.READMESTATISTICS }}
          
          # Tu nombre de usuario
          user: xsha256
          
          # Configuración de la plantilla (estilo oscuro y estadísticas a fondo)
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          
          # Esto obliga a contar todo tu historial y repositorios privados
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
